Error output test

CondaError: Run 'conda init' before 'conda activate'

2024-07-14 15:16:32.040548: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-14 15:16:32.040642: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-14 15:16:32.125393: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-14 15:16:32.315620: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-14 15:16:34.533080: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/data/users1/mdoan4/dev/wirehead/examples/synthseg_slurm/worker.py", line 46, in <module>
    wirehead_generator.run_generator()
  File "/data/users1/mdoan4/dev/wirehead/wirehead/generator.py", line 127, in run_generator
    self.generate_and_insert()
  File "/data/users1/mdoan4/dev/wirehead/wirehead/generator.py", line 112, in generate_and_insert
    data = next(self.generator)
  File "/data/users1/mdoan4/dev/wirehead/examples/synthseg_slurm/worker.py", line 19, in create_generator
    DATA_FILES[training_seg],
TypeError: list indices must be integers or slices, not str
